# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The UX Thinker
email: matt@theuxthinker.com
description: > # this means to ignore newlines until "baseurl:"
  Matt Johnson is a Senior UX Designer and Developer at Visual Logic in Waterloo Iowa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uxthinker.github.io" # the base hostname & protocol for your site
twitter_username: themattj
github_username:  uxthinker

# Build settings
markdown: kramdown
